server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    stream:
      username: guest
      password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrpark219/msa-study
          default-label: main
          search-paths: config-file/

management:
  endpoints:
    web:
      exposure:
        include: health,busrefresh

encrypt:
#  key: testKey
  key-store:
    location: file://${user.home}/workspace/msa-study/keystore/apiEncryptionKey.kys
    password: 1q2w3e4r
    alias: apiEncryptionKey